hooks:
- active: false
  config:
    content_type: json
    insecure_ssl: '0'
    secret: '********'
    url: http://example.com
  events:
  - push
  name: web
members:
  dothub-bot:
    role: admin
  mariocj89:
    role: admin
options:
  billing_email: mariocj89+dothub@gmail.com
  company: null
  description: Test organization for dothub integration tests
  email: null
  location: null
  name: Dothub Test Org
teams:
  sample-repo:
    description: sample-repo
    members:
      dothub-bot:
        role: maintainer
    permission: pull
    privacy: closed
    repositories: {}
