collaborators:
  dothub-bot:
    permission: admin
  mariocj89:
    permission: admin
hooks:
- active: true
  config:
    domain: notify.travis-ci.org
  events:
  - push
  name: travis
- active: true
  config:
    content_type: form
    insecure_ssl: '0'
    url: https://exampleurl.com
  events:
  - push
  name: web
labels:
  bug:
    color: '000000'
  feature:
    color: 009800
  new draw:
    color: fbca04
  technical:
    color: 0052cc
  urgent:
    color: e11d21
options:
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  has_downloads: true
  has_issues: true
  has_wiki: false
  private: false
